// Generated by scripts/generate-tokens.mjs. Do not edit.
import SwiftUI

public enum NTOTokens {
    public enum Color {
        public static let black = SwiftUI.Color(red: 0, green: 0, blue: 0)
        public static let canvas = SwiftUI.Color(red: 0.0392156862745098, green: 0.0392156862745098, blue: 0.0392156862745098)
        public static let white = SwiftUI.Color(red: 1, green: 1, blue: 1)
        public static let paper = SwiftUI.Color(red: 0.9490196078431372, green: 0.9490196078431372, blue: 0.9490196078431372)
        public static let muted = SwiftUI.Color(red: 0.6392156862745098, green: 0.6392156862745098, blue: 0.6392156862745098)
        public static let line = SwiftUI.Color(red: 0.2196078431372549, green: 0.2196078431372549, blue: 0.2196078431372549)
    }
    public enum Spacing {
        public static let xs: Double = 4
        public static let sm: Double = 8
        public static let md: Double = 16
        public static let lg: Double = 24
        public static let xl: Double = 40
        public static let xxl: Double = 64
    }
    public enum Typography {
        public static let caption: Double = 12
        public static let body: Double = 16
        public static let title: Double = 32
        public static let display: Double = 72
    }
    public enum Motion {
        public static let fast: Double = 0.12
        public static let standard: Double = 0.24
        public static let reveal: Double = 0.6
    }
}
