#!/bin/sh
set -eu
NTO_NODE_DIR="$HOME/.local/share/nto/toolchains/node-v24.21.0-darwin-arm64/bin"
if [ -d "$NTO_NODE_DIR" ]; then export PATH="$NTO_NODE_DIR:$PATH"; fi
NTO_CONTAINER_BIN="$HOME/.local/share/nto/toolchains/containers/bin"
if [ -d "$NTO_CONTAINER_BIN" ]; then export PATH="$NTO_CONTAINER_BIN:$PATH"; fi
if [ -z "${DOCKER_HOST:-}" ] && [ -S "$HOME/.lima/nto/sock/docker.sock" ]; then
  export DOCKER_HOST="unix://$HOME/.lima/nto/sock/docker.sock"
fi
exec pnpm "$@"
